name = "midulink"
type = "javascript"

workers_dev = true
account_id = "599228840df452ef6b4df93a2b67c0ee"
route = ""
zone_id = ""

kv_namespaces = [
  { binding = "URLS", id = "5d72e7f7bff7451493c7e07a43bdfc3b", preview_id = "879ecdf303634fd290aaf857dc3b2b7a" }
]